
	Python anaconda is now loaded in your environment.

Preparing directory /jmain01/home/JAD017/sjr01/dxg49-sjr01/kfac-curvature/out//CIFAR100/VGG16/SWA/lr=0.01_wd=1e-05_swastart=161_swalr=0.0005/
Traceback (most recent call last):
  File "../run_swag.py", line 56, in <module>
    os.makedirs(args.dir, exist_ok=True)
  File "/jmain01/home/JAD017/sjr02/dxg49-sjr02/.conda/envs/diegorubin/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/jmain01/home/JAD017/sjr02/dxg49-sjr02/.conda/envs/diegorubin/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/jmain01/home/JAD017/sjr02/dxg49-sjr02/.conda/envs/diegorubin/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/jmain01/home/JAD017/sjr02/dxg49-sjr02/.conda/envs/diegorubin/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/jmain01/home/JAD017/sjr01/dxg49-sjr01'
